name: tesseroid-variable-density
channels:
  - conda-forge
dependencies:
  - basemap=1.2.0
  - basemap-data-hires=1.2.0
  - cython=0.26.1
  - fatiando=0.5
  - future=0.18.2
  - gcc_linux-64=7.5.0
  - jupyter=1.0.0
  - matplotlib=2.2.3
  - numba=0.43.1
  - numpy=1.11.3
  - pandas=0.23.4
  - pillow=6.2.1
  - proselint=0.10.2
  - pytest=4.6.4
  - python=2.7.15
  - scipy=1.2.1
  - sympy=1.5.1
